%% =========================================================================
%  BLDC FOC + SMO - modular Simulink model auto-builder
%  =========================================================================
%  Auto-generates a block-diagram model following the FOC signal flow:
%  Speed_Reference -> Speed_Controller -> Current_Controller -> Inv_Park
%  -> Inv_Clarke -> SVPWM -> BLDC_Motor -> Clarke -> Park -> feedback,
%  with an SMO module providing sensorless theta/speed closed-loop feedback.
%  =========================================================================

if exist('FOC_MODEL_NAME', 'var')
    requestedModelName = FOC_MODEL_NAME;
else
    requestedModelName = '';
end
clearvars -except requestedModelName;
clc; close all;

projectRoot = fileparts(mfilename('fullpath'));
addpath(projectRoot);
addpath(fullfile(projectRoot, 'foc_functions'));

motor_parameters;

cacheFolder = fullfile(pwd, 'simulink_cache');
codegenFolder = fullfile(pwd, 'simulink_codegen');
if ~exist(cacheFolder, 'dir'), mkdir(cacheFolder); end
if ~exist(codegenFolder, 'dir'), mkdir(codegenFolder); end
Simulink.fileGenControl('set', ...
    'CacheFolder', cacheFolder, ...
    'CodeGenFolder', codegenFolder, ...
    'createDir', true);
clear mex;
clear functions;

if isempty(requestedModelName)
    baseModelName = 'BLDC_FOC_Model';
else
    baseModelName = requestedModelName;
end
modelName = baseModelName;

if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
if exist([modelName '.slx'], 'file')
    modelName = [baseModelName '_' datestr(now, 'yyyymmdd_HHMMSS')];
end

new_system(modelName);
set_param(modelName, 'Solver', 'FixedStepDiscrete');
set_param(modelName, 'FixedStep', num2str(sim_params.Ts));
set_param(modelName, 'StopTime', num2str(sim_params.Tend));
set_param(modelName, 'ReturnWorkspaceOutputs', 'on');
set_param(modelName, 'SaveFormat', 'StructureWithTime');

fprintf('Building modular Simulink model: %s\n', modelName);

%% Top-level source and module blocks
add_block('simulink/Sources/Clock', [modelName '/Clock'], ...
    'Position', [30 95 60 125]);

add_codegen_subsystem(modelName, 'Speed_Reference', [100 70 245 150], ...
    {'t'}, {'w_ref'}, speed_ref_script(sim_params));

add_codegen_subsystem(modelName, 'Speed_Controller', [300 55 470 170], ...
    {'w_ref', 'w_fb'}, {'iq_ref', 'id_ref'}, speed_controller_script(sim_params, pid_speed, motor));

add_codegen_subsystem(modelName, 'Current_Controller', [530 35 730 205], ...
    {'id_ref', 'iq_ref', 'id_fb', 'iq_fb', 'omega_m'}, {'Vd', 'Vq'}, ...
    current_controller_script(sim_params, pwm, pid_id, pid_iq, motor));

add_codegen_subsystem(modelName, 'Inv_Park', [790 65 955 175], ...
    {'Vd', 'Vq', 'theta_e'}, {'V_alpha', 'V_beta'}, inv_park_script());

add_codegen_subsystem(modelName, 'Inv_Clarke', [1015 55 1180 185], ...
    {'V_alpha', 'V_beta'}, {'Va_ref', 'Vb_ref', 'Vc_ref'}, inv_clarke_script());

add_codegen_subsystem(modelName, 'SVPWM', [1240 45 1415 195], ...
    {'Va_ref', 'Vb_ref', 'Vc_ref'}, {'Va', 'Vb', 'Vc', 'duty_a', 'duty_b', 'duty_c'}, ...
    svpwm_module_script(motor));

add_codegen_subsystem(modelName, 'BLDC_Motor', [1480 35 1690 230], ...
    {'Va', 'Vb', 'Vc', 'TL'}, {'ia', 'ib', 'ic', 'theta_e', 'omega_m', 'Te'}, ...
    motor_model_script(sim_params, motor));

add_codegen_subsystem(modelName, 'Clarke', [990 330 1155 450], ...
    {'ia', 'ib', 'ic'}, {'i_alpha', 'i_beta'}, clarke_script());

add_codegen_subsystem(modelName, 'Park', [1215 325 1380 455], ...
    {'i_alpha', 'i_beta', 'theta_e'}, {'id', 'iq'}, park_script());

add_codegen_subsystem(modelName, 'SMO', [1480 310 1710 500], ...
    {'Va', 'Vb', 'Vc', 'ia', 'ib', 'ic', 'theta_true', 'omega_true', 't'}, ...
    {'theta_ctrl', 'omega_ctrl', 'theta_smo', 'omega_smo', 'theta_err'}, ...
    smo_module_script(sim_params, smo, motor));

add_block('simulink/Sources/Step', [modelName '/Load_Torque'], ...
    'Time', num2str(sim_params.load_time), ...
    'Before', '0', ...
    'After', num2str(sim_params.load_torque), ...
    'Position', [1280 235 1330 265]);

%% Feedback delays
delayNames = {'ia', 'ib', 'ic', 'theta_e', 'omega_m', 'theta_ctrl', 'omega_ctrl'};
delayPos = [
    1745 250 1785 280;
    1745 290 1785 320;
    1745 330 1785 360;
    1745 370 1785 400;
    1745 410 1785 440;
    1745 470 1785 500;
    1745 510 1785 540
];
for idx = 1:numel(delayNames)
    add_block('simulink/Discrete/Unit Delay', [modelName '/Delay_' delayNames{idx}], ...
        'InitialCondition', '0', ...
        'SampleTime', num2str(sim_params.Ts), ...
        'Position', delayPos(idx, :));
end

%% Main forward path
add_line(modelName, 'Clock/1', 'Speed_Reference/1', 'autorouting', 'smart');
add_line(modelName, 'Speed_Reference/1', 'Speed_Controller/1', 'autorouting', 'smart');
add_line(modelName, 'Delay_omega_ctrl/1', 'Speed_Controller/2', 'autorouting', 'smart');

add_line(modelName, 'Speed_Controller/2', 'Current_Controller/1', 'autorouting', 'smart'); % id_ref
add_line(modelName, 'Speed_Controller/1', 'Current_Controller/2', 'autorouting', 'smart'); % iq_ref
add_line(modelName, 'Park/1', 'Current_Controller/3', 'autorouting', 'smart'); % id
add_line(modelName, 'Park/2', 'Current_Controller/4', 'autorouting', 'smart'); % iq
add_line(modelName, 'Delay_omega_ctrl/1', 'Current_Controller/5', 'autorouting', 'smart');

add_line(modelName, 'Current_Controller/1', 'Inv_Park/1', 'autorouting', 'smart');
add_line(modelName, 'Current_Controller/2', 'Inv_Park/2', 'autorouting', 'smart');
add_line(modelName, 'Delay_theta_ctrl/1', 'Inv_Park/3', 'autorouting', 'smart');

add_line(modelName, 'Inv_Park/1', 'Inv_Clarke/1', 'autorouting', 'smart');
add_line(modelName, 'Inv_Park/2', 'Inv_Clarke/2', 'autorouting', 'smart');

add_line(modelName, 'Inv_Clarke/1', 'SVPWM/1', 'autorouting', 'smart');
add_line(modelName, 'Inv_Clarke/2', 'SVPWM/2', 'autorouting', 'smart');
add_line(modelName, 'Inv_Clarke/3', 'SVPWM/3', 'autorouting', 'smart');

add_line(modelName, 'SVPWM/1', 'BLDC_Motor/1', 'autorouting', 'smart');
add_line(modelName, 'SVPWM/2', 'BLDC_Motor/2', 'autorouting', 'smart');
add_line(modelName, 'SVPWM/3', 'BLDC_Motor/3', 'autorouting', 'smart');
add_line(modelName, 'Load_Torque/1', 'BLDC_Motor/4', 'autorouting', 'smart');

%% Motor feedback path
add_line(modelName, 'BLDC_Motor/1', 'Delay_ia/1', 'autorouting', 'smart');
add_line(modelName, 'BLDC_Motor/2', 'Delay_ib/1', 'autorouting', 'smart');
add_line(modelName, 'BLDC_Motor/3', 'Delay_ic/1', 'autorouting', 'smart');
add_line(modelName, 'BLDC_Motor/4', 'Delay_theta_e/1', 'autorouting', 'smart');
add_line(modelName, 'BLDC_Motor/5', 'Delay_omega_m/1', 'autorouting', 'smart');

add_line(modelName, 'Delay_ia/1', 'Clarke/1', 'autorouting', 'smart');
add_line(modelName, 'Delay_ib/1', 'Clarke/2', 'autorouting', 'smart');
add_line(modelName, 'Delay_ic/1', 'Clarke/3', 'autorouting', 'smart');

add_line(modelName, 'Clarke/1', 'Park/1', 'autorouting', 'smart');
add_line(modelName, 'Clarke/2', 'Park/2', 'autorouting', 'smart');
add_line(modelName, 'Delay_theta_ctrl/1', 'Park/3', 'autorouting', 'smart');

%% SMO feedback path
add_line(modelName, 'SVPWM/1', 'SMO/1', 'autorouting', 'smart');
add_line(modelName, 'SVPWM/2', 'SMO/2', 'autorouting', 'smart');
add_line(modelName, 'SVPWM/3', 'SMO/3', 'autorouting', 'smart');
add_line(modelName, 'Delay_ia/1', 'SMO/4', 'autorouting', 'smart');
add_line(modelName, 'Delay_ib/1', 'SMO/5', 'autorouting', 'smart');
add_line(modelName, 'Delay_ic/1', 'SMO/6', 'autorouting', 'smart');
add_line(modelName, 'Delay_theta_e/1', 'SMO/7', 'autorouting', 'smart');
add_line(modelName, 'Delay_omega_m/1', 'SMO/8', 'autorouting', 'smart');
add_line(modelName, 'Clock/1', 'SMO/9', 'autorouting', 'smart');
add_line(modelName, 'SMO/1', 'Delay_theta_ctrl/1', 'autorouting', 'smart');
add_line(modelName, 'SMO/2', 'Delay_omega_ctrl/1', 'autorouting', 'smart');

%% Scopes and workspace logging
add_scope_mux(modelName, 'Speed_Scope', [250 590 310 640], ...
    {'Speed_Reference/1', 'Delay_omega_m/1', 'SMO/4'}, {'w_ref', 'omega_m', 'omega_smo'});
add_scope_mux(modelName, 'DQ_Current_Scope', [530 590 590 640], ...
    {'Speed_Controller/2', 'Park/1', 'Speed_Controller/1', 'Park/2'}, {'id_ref', 'id', 'iq_ref', 'iq'});
add_scope_mux(modelName, 'Phase_Current_Scope', [810 590 870 640], ...
    {'Delay_ia/1', 'Delay_ib/1', 'Delay_ic/1'}, {'ia', 'ib', 'ic'});
add_scope_mux(modelName, 'Voltage_Scope', [1090 590 1150 640], ...
    {'SVPWM/1', 'SVPWM/2', 'SVPWM/3'}, {'Va', 'Vb', 'Vc'});
add_scope_mux(modelName, 'Torque_Scope', [1370 590 1430 640], ...
    {'BLDC_Motor/6', 'Load_Torque/1'}, {'Te', 'TL'});
add_scope_mux(modelName, 'SMO_Scope', [1650 590 1710 640], ...
    {'Delay_theta_e/1', 'SMO/3', 'SMO/5'}, {'theta_e', 'theta_smo', 'theta_err'});

add_block('simulink/Signal Routing/Mux', [modelName '/Data_Mux'], ...
    'Inputs', '17', ...
    'Position', [1860 70 1865 460]);
add_block('simulink/Sinks/To Workspace', [modelName '/foc_data'], ...
    'VariableName', 'foc_data', ...
    'SaveFormat', 'StructureWithTime', ...
    'Position', [1940 235 2040 275]);

dataSignals = {'Speed_Reference/1', 'Delay_omega_m/1', 'SMO/4', ...
    'Park/1', 'Speed_Controller/1', 'Park/2', ...
    'Delay_ia/1', 'Delay_ib/1', 'Delay_ic/1', ...
    'BLDC_Motor/6', 'Load_Torque/1', ...
    'Delay_theta_e/1', 'SMO/3', 'SMO/5', ...
    'SVPWM/4', 'SVPWM/5', 'SVPWM/6'};
for idx = 1:numel(dataSignals)
    add_line(modelName, dataSignals{idx}, ['Data_Mux/' num2str(idx)], 'autorouting', 'smart');
end
add_line(modelName, 'Data_Mux/1', 'foc_data/1', 'autorouting', 'smart');

add_block('built-in/Note', [modelName '/Title_Note'], ...
    'Position', [520 5 1240 45], ...
    'Text', 'BLDC Motor FOC + SMO Sensorless Closed Loop - Modular Auto Generated Model', ...
    'FontSize', '14', ...
    'FontWeight', 'bold', ...
    'BackgroundColor', '[0.9 0.95 1.0]');

add_block('built-in/Note', [modelName '/Data_Note'], ...
    'Position', [1810 500 2070 575], ...
    'Text', sprintf(['foc_data order:\\n' ...
    '1 w_ref, 2 omega_m, 3 omega_smo, 4 id, 5 iq_ref, 6 iq,\\n' ...
    '7 ia, 8 ib, 9 ic, 10 Te, 11 TL, 12 theta_e, 13 theta_smo,\\n' ...
    '14 theta_err, 15 duty_a, 16 duty_b, 17 duty_c']), ...
    'FontSize', '9', ...
    'BackgroundColor', '[1.0 1.0 0.85]');

%% Apply custom visual styling and create Area Annotations
fprintf('Applying custom block styling and area annotations...\n');

% 1. Create Area Annotations for visual grouping
add_block('built-in/Area', [modelName '/Control & Reference'], 'Position', [80 15 750 220]);
add_block('built-in/Area', [modelName '/Modulation & Forward Transforms'], 'Position', [770 15 1435 220]);
add_block('built-in/Area', [modelName '/Motor Plant & Load'], 'Position', [1460 15 1710 280]);
add_block('built-in/Area', [modelName '/Feedback Transformations'], 'Position', [970 290 1400 480]);
add_block('built-in/Area', [modelName '/Sliding Mode Observer (SMO)'], 'Position', [1460 290 1730 520]);
add_block('built-in/Area', [modelName '/Monitoring Scopes'], 'Position', [100 560 1800 680]);

% Style the Area Annotations
set_param([modelName '/Control & Reference'], 'BackgroundColor', mat2str([0.92 0.96 1.0]), 'FontSize', '11', 'FontWeight', 'bold');
set_param([modelName '/Modulation & Forward Transforms'], 'BackgroundColor', mat2str([1.0 0.95 1.0]), 'FontSize', '11', 'FontWeight', 'bold');
set_param([modelName '/Motor Plant & Load'], 'BackgroundColor', mat2str([0.92 0.98 0.92]), 'FontSize', '11', 'FontWeight', 'bold');
set_param([modelName '/Feedback Transformations'], 'BackgroundColor', mat2str([1.0 1.0 0.92]), 'FontSize', '11', 'FontWeight', 'bold');
set_param([modelName '/Sliding Mode Observer (SMO)'], 'BackgroundColor', mat2str([0.92 0.98 0.98]), 'FontSize', '11', 'FontWeight', 'bold');
set_param([modelName '/Monitoring Scopes'], 'BackgroundColor', mat2str([0.97 0.97 0.97]), 'FontSize', '11', 'FontWeight', 'bold');

% 2. Define block color schemes
colorRef = [1.0 0.85 0.85];      % Soft Red for Reference & Load inputs
colorCtrl = [0.8 0.9 1.0];       % Soft Blue for PI Controllers
colorTrans = [1.0 1.0 0.8];      % Soft Yellow for Coordinate Transformations
colorPwm = [0.9 0.85 1.0];       % Soft Purple for SVPWM Modulation
colorMotor = [0.8 0.95 0.8];     % Soft Green for Motor Model
colorSmo = [0.8 1.0 1.0];        % Soft Teal for SMO sliding mode observer
colorDelay = [0.92 0.92 0.92];   % Light Gray for feedback delays
colorWorkspace = [0.9 0.9 0.9];  % Pale Gray for workspace output

% 3. Apply styles to standard blocks
set_param([modelName '/Speed_Reference'], 'BackgroundColor', mat2str(colorRef), 'DropShadow', 'on', 'FontSize', '10', 'FontWeight', 'bold');
set_param([modelName '/Load_Torque'], 'BackgroundColor', mat2str(colorRef), 'DropShadow', 'on', 'FontSize', '10', 'FontWeight', 'bold');
set_param([modelName '/Clock'], 'BackgroundColor', mat2str(colorDelay), 'ShowName', 'off');

set_param([modelName '/Speed_Controller'], 'BackgroundColor', mat2str(colorCtrl), 'DropShadow', 'on', 'FontSize', '10', 'FontWeight', 'bold');
set_param([modelName '/Current_Controller'], 'BackgroundColor', mat2str(colorCtrl), 'DropShadow', 'on', 'FontSize', '10', 'FontWeight', 'bold');

set_param([modelName '/Inv_Park'], 'BackgroundColor', mat2str(colorTrans), 'DropShadow', 'on', 'FontSize', '10', 'FontWeight', 'bold');
set_param([modelName '/Inv_Clarke'], 'BackgroundColor', mat2str(colorTrans), 'DropShadow', 'on', 'FontSize', '10', 'FontWeight', 'bold');

set_param([modelName '/SVPWM'], 'BackgroundColor', mat2str(colorPwm), 'DropShadow', 'on', 'FontSize', '10', 'FontWeight', 'bold');

set_param([modelName '/BLDC_Motor'], 'BackgroundColor', mat2str(colorMotor), 'DropShadow', 'on', 'FontSize', '10', 'FontWeight', 'bold');

set_param([modelName '/Clarke'], 'BackgroundColor', mat2str(colorTrans), 'DropShadow', 'on', 'FontSize', '10', 'FontWeight', 'bold');
set_param([modelName '/Park'], 'BackgroundColor', mat2str(colorTrans), 'DropShadow', 'on', 'FontSize', '10', 'FontWeight', 'bold');

set_param([modelName '/SMO'], 'BackgroundColor', mat2str(colorSmo), 'DropShadow', 'on', 'FontSize', '10', 'FontWeight', 'bold');

% Style delay blocks
for idx = 1:numel(delayNames)
    set_param([modelName '/Delay_' delayNames{idx}], 'BackgroundColor', mat2str(colorDelay), 'ShowName', 'off');
end

% (Note styles applied directly inside add_block above)

% Style Workspace & Mux
set_param([modelName '/foc_data'], 'BackgroundColor', mat2str(colorWorkspace), 'DropShadow', 'on');
set_param([modelName '/Data_Mux'], 'ShowName', 'off', 'BackgroundColor', 'black');

% Disable auto-arrange to preserve precise manual alignment and grouping
% Simulink.BlockDiagram.arrangeSystem(modelName);
save_system(modelName);
assignin('base', 'modelName', modelName);
assignin('base', 'generatedModelName', modelName);

fprintf('\n============================================\n');
fprintf('  Modular Simulink model generated successfully\n');
fprintf('============================================\n');
fprintf('  Model: %s.slx\n', modelName);
fprintf('  Run:   sim(''%s'')\n', modelName);
fprintf('  Data:  foc_data (StructureWithTime)\n');
fprintf('============================================\n');

if usejava('desktop') && feature('ShowFigureWindows')
    open_system(modelName);
end

%% Local builder helpers
function add_codegen_subsystem(modelName, name, pos, inNames, outNames, scriptText)
    path = [modelName '/' name];
    add_block('built-in/SubSystem', path, 'Position', pos);
    safe_clear_subsys(path);

    nIn = numel(inNames);
    nOut = numel(outNames);

    for k = 1:nIn
        y = 35 + (k-1)*35;
        add_block('built-in/Inport', [path '/' inNames{k}], ...
            'Position', [25 y 55 y+14]);
    end

    add_block('simulink/User-Defined Functions/MATLAB Function', [path '/Fcn'], ...
        'Position', [150 45 260 max(95, 45+nIn*25)]);
    rt = sfroot;
    chart = rt.find('-isa', 'Stateflow.EMChart', 'Path', [path '/Fcn']);
    chart.Script = scriptText;

    if nIn == 1
        add_line(path, [inNames{1} '/1'], 'Fcn/1', 'autorouting', 'smart');
    else
        add_block('simulink/Signal Routing/Mux', [path '/Mux'], ...
            'Inputs', num2str(nIn), ...
            'Position', [95 30 100 45+nIn*35]);
        for k = 1:nIn
            add_line(path, [inNames{k} '/1'], ['Mux/' num2str(k)], 'autorouting', 'smart');
        end
        add_line(path, 'Mux/1', 'Fcn/1', 'autorouting', 'smart');
    end

    if nOut == 1
        add_block('built-in/Outport', [path '/' outNames{1}], ...
            'Position', [335 55 365 69]);
        add_line(path, 'Fcn/1', [outNames{1} '/1'], 'autorouting', 'smart');
    else
        add_block('simulink/Signal Routing/Demux', [path '/Demux'], ...
            'Outputs', num2str(nOut), ...
            'Position', [300 35 305 45+nOut*35]);
        add_line(path, 'Fcn/1', 'Demux/1', 'autorouting', 'smart');
        for k = 1:nOut
            y = 35 + (k-1)*35;
            add_block('built-in/Outport', [path '/' outNames{k}], ...
                'Position', [355 y 385 y+14]);
            add_line(path, ['Demux/' num2str(k)], [outNames{k} '/1'], 'autorouting', 'smart');
        end
    end
end

function add_scope_mux(modelName, scopeName, scopePos, signalPaths, ~)
    muxName = [scopeName '_Mux'];
    add_block('simulink/Signal Routing/Mux', [modelName '/' muxName], ...
        'Inputs', num2str(numel(signalPaths)), ...
        'Position', [scopePos(1)-90 scopePos(2)-10 scopePos(1)-85 scopePos(4)+10]);
    add_block('simulink/Sinks/Scope', [modelName '/' scopeName], ...
        'Position', scopePos);
    
    % Apply visual styles to Scope and Mux
    set_param([modelName '/' scopeName], 'BackgroundColor', '[0.95 0.95 0.95]', 'DropShadow', 'on');
    set_param([modelName '/' muxName], 'ShowName', 'off', 'BackgroundColor', 'black');

    for k = 1:numel(signalPaths)
        add_line(modelName, signalPaths{k}, [muxName '/' num2str(k)], 'autorouting', 'smart');
    end
    add_line(modelName, [muxName '/1'], [scopeName '/1'], 'autorouting', 'smart');
end

%% MATLAB Function block scripts
function script = speed_ref_script(sim_params)
    wRef = sim_params.speed_ref * 2*pi/60;
    slope = wRef / 0.05;
    script = sprintf(['function y = fcn(t)\n' ...
        '%%#codegen\n' ...
        'if t < 0.01\n' ...
        '    y = 0;\n' ...
        'elseif t < 0.06\n' ...
        '    y = %.17g * (t - 0.01);\n' ...
        'else\n' ...
        '    y = %.17g;\n' ...
        'end\n' ...
        'end\n'], slope, wRef);
end

function script = speed_controller_script(sim_params, pid_speed, motor)
    script = sprintf(['function y = fcn(u)\n' ...
        '%%#codegen\n' ...
        'persistent integ counter iq_ref\n' ...
        'if isempty(integ), integ=0; counter=0; iq_ref=0; end\n' ...
        'dt=%.17g; Ts=%.17g; Kp=%.17g; Ki=%.17g; outMax=%.17g; outMin=%.17g;\n' ...
        'w_ref=u(1); w_fb=u(2); counter=counter+dt;\n' ...
        'if counter >= Ts\n' ...
        '    counter=0; err=w_ref-w_fb; integ=integ+Ki*err*Ts; unsat=Kp*err+integ;\n' ...
        '    iq_ref=min(outMax,max(outMin,unsat));\n' ...
        '    if iq_ref ~= unsat, integ=integ-Ki*err*Ts; end\n' ...
        'end\n' ...
        'y=zeros(2,1); y(1)=iq_ref; y(2)=0;\n' ...
        'end\n'], sim_params.Ts, 10*(1/20000), pid_speed.Kp, pid_speed.Ki, motor.max_current, -motor.max_current);
end

function script = current_controller_script(sim_params, pwm, pid_id, pid_iq, motor)
    script = sprintf(['function y = fcn(u)\n' ...
        '%%#codegen\n' ...
        'persistent int_id int_iq counter vd vq\n' ...
        'if isempty(int_id), int_id=0; int_iq=0; counter=0; vd=0; vq=0; end\n' ...
        'dt=%.17g; Ts=%.17g; Vdc=%.17g; Ld=%.17g; Lq=%.17g; flux=%.17g; pp=%.17g;\n' ...
        'id_ref=u(1); iq_ref=u(2); id=u(3); iq=u(4); omega_m=u(5); counter=counter+dt;\n' ...
        'if counter >= Ts\n' ...
        '    counter=0;\n' ...
        '    err=id_ref-id; int_id=int_id+%.17g*err*Ts; unsat=%.17g*err+int_id; vd=min(%.17g,max(%.17g,unsat)); if vd~=unsat, int_id=int_id-%.17g*err*Ts; end\n' ...
        '    err=iq_ref-iq; int_iq=int_iq+%.17g*err*Ts; unsat=%.17g*err+int_iq; vq=min(%.17g,max(%.17g,unsat)); if vq~=unsat, int_iq=int_iq-%.17g*err*Ts; end\n' ...
        '    omega_e=omega_m*pp; vd=vd-omega_e*Lq*iq; vq=vq+omega_e*Ld*id+omega_e*flux;\n' ...
        '    Vmax=Vdc/sqrt(3); Vmag=sqrt(vd*vd+vq*vq); if Vmag>Vmax, vd=vd*Vmax/Vmag; vq=vq*Vmax/Vmag; end\n' ...
        'end\n' ...
        'y=zeros(2,1); y(1)=vd; y(2)=vq;\n' ...
        'end\n'], sim_params.Ts, pwm.Ts, motor.Vdc, motor.Ld, motor.Lq, motor.flux, motor.pole_pairs, ...
        pid_id.Ki, pid_id.Kp, pid_id.max, pid_id.min, pid_id.Ki, ...
        pid_iq.Ki, pid_iq.Kp, pid_iq.max, pid_iq.min, pid_iq.Ki);
end

function script = inv_park_script()
    script = ['function y = fcn(u)' newline ...
        '%#codegen' newline ...
        'vd=u(1); vq=u(2); th=u(3);' newline ...
        'y=zeros(2,1); y(1)=vd*cos(th)-vq*sin(th); y(2)=vd*sin(th)+vq*cos(th);' newline ...
        'end'];
end

function script = inv_clarke_script()
    script = ['function y = fcn(u)' newline ...
        '%#codegen' newline ...
        'va=u(1); vb=u(2);' newline ...
        'y=zeros(3,1); y(1)=va; y(2)=-0.5*va+sqrt(3)/2*vb; y(3)=-0.5*va-sqrt(3)/2*vb;' newline ...
        'end'];
end

function script = svpwm_module_script(motor)
    script = sprintf(['function y = fcn(u)\n' ...
        '%%#codegen\n' ...
        'Vdc=%.17g; va=u(1); vb=u(2); vc=u(3);\n' ...
        'vmax=max(max(va,vb),vc); vmin=min(min(va,vb),vc); voff=-0.5*(vmax+vmin);\n' ...
        'da=min(1,max(0,0.5+(va+voff)/Vdc)); db=min(1,max(0,0.5+(vb+voff)/Vdc)); dc=min(1,max(0,0.5+(vc+voff)/Vdc));\n' ...
        'y=zeros(6,1); y(1)=(2*da-1)*Vdc/2; y(2)=(2*db-1)*Vdc/2; y(3)=(2*dc-1)*Vdc/2; y(4)=da; y(5)=db; y(6)=dc;\n' ...
        'end\n'], motor.Vdc);
end

function script = motor_model_script(sim_params, motor)
    script = sprintf(['function y = fcn(u)\n' ...
        '%%#codegen\n' ...
        'persistent ia ib ic th wm\n' ...
        'if isempty(ia), ia=0; ib=0; ic=0; th=0; wm=0; end\n' ...
        'dt=%.17g; Rs=%.17g; Ld=%.17g; Lq=%.17g; flux=%.17g; pp=%.17g; J=%.17g; B=%.17g;\n' ...
        'va=u(1); vb=u(2); vc=u(3); TL=u(4); we=wm*pp;\n' ...
        'valpha=(2/3)*(va-0.5*vb-0.5*vc); vbeta=(2/3)*(sqrt(3)/2*vb-sqrt(3)/2*vc);\n' ...
        'vd=valpha*cos(th)+vbeta*sin(th); vq=-valpha*sin(th)+vbeta*cos(th);\n' ...
        'ialpha=(2/3)*(ia-0.5*ib-0.5*ic); ibeta=(2/3)*(sqrt(3)/2*ib-sqrt(3)/2*ic);\n' ...
        'id=ialpha*cos(th)+ibeta*sin(th); iq=-ialpha*sin(th)+ibeta*cos(th);\n' ...
        'did=(vd-Rs*id+we*Lq*iq)/Ld; diq=(vq-Rs*iq-we*Ld*id-we*flux)/Lq;\n' ...
        'idn=id+did*dt; iqn=iq+diq*dt; Te=1.5*pp*(flux*iqn+(Ld-Lq)*idn*iqn);\n' ...
        'wm=wm+(Te-TL-B*wm)/J*dt; th=mod(th+wm*pp*dt,2*pi);\n' ...
        'ialpha=idn*cos(th)-iqn*sin(th); ibeta=idn*sin(th)+iqn*cos(th);\n' ...
        'ia=ialpha; ib=-0.5*ialpha+sqrt(3)/2*ibeta; ic=-0.5*ialpha-sqrt(3)/2*ibeta;\n' ...
        'y=zeros(6,1); y(1)=ia; y(2)=ib; y(3)=ic; y(4)=th; y(5)=wm; y(6)=Te;\n' ...
        'end\n'], sim_params.Ts, motor.Rs, motor.Ld, motor.Lq, motor.flux, motor.pole_pairs, motor.J, motor.B);
end

function script = clarke_script()
    script = ['function y = fcn(u)' newline ...
        '%#codegen' newline ...
        'ia=u(1); ib=u(2); ic=u(3);' newline ...
        'y=zeros(2,1); y(1)=(2/3)*(ia-0.5*ib-0.5*ic); y(2)=(2/3)*(sqrt(3)/2*ib-sqrt(3)/2*ic);' newline ...
        'end'];
end

function script = park_script()
    script = ['function y = fcn(u)' newline ...
        '%#codegen' newline ...
        'ialpha=u(1); ibeta=u(2); th=u(3);' newline ...
        'y=zeros(2,1); y(1)=ialpha*cos(th)+ibeta*sin(th); y(2)=-ialpha*sin(th)+ibeta*cos(th);' newline ...
        'end'];
end

function script = smo_module_script(sim_params, smo, motor)
    useSmo = double(sim_params.use_smo_feedback);
    script = sprintf(['function y = fcn(u)\n' ...
        '%%#codegen\n' ...
        'persistent ih_a ih_b eh_a eh_b th_h we_h\n' ...
        'if isempty(ih_a), ih_a=0; ih_b=0; eh_a=0; eh_b=0; th_h=0; we_h=0; end\n' ...
        'Vdc=%.17g; dt=%.17g; Rs=%.17g; Ls=%.17g; pp=%.17g; K=%.17g; boundary=%.17g; emfCut=%.17g; speedCut=%.17g; minEmf=%.17g; enableT=%.17g; useSmo=%d;\n' ...
        'va=u(1); vb=u(2); vc=u(3); ia=u(4); ib=u(5); ic=u(6); th_true=u(7); wm_true=u(8); t=u(9);\n' ...
        'v_alpha=(2/3)*(va-0.5*vb-0.5*vc); v_beta=(2/3)*(sqrt(3)/2*vb-sqrt(3)/2*vc);\n' ...
        'i_alpha=(2/3)*(ia-0.5*ib-0.5*ic); i_beta=(2/3)*(sqrt(3)/2*ib-sqrt(3)/2*ic);\n' ...
        'za=K*min(1,max(-1,(ih_a-i_alpha)/boundary)); zb=K*min(1,max(-1,(ih_b-i_beta)/boundary));\n' ...
        'ih_a=ih_a+dt/Ls*(v_alpha-Rs*ih_a-za); ih_b=ih_b+dt/Ls*(v_beta-Rs*ih_b-zb);\n' ...
        'a=dt*emfCut/(1+dt*emfCut); eh_a=eh_a+a*(za-eh_a); eh_b=eh_b+a*(zb-eh_b);\n' ...
        'if sqrt(eh_a*eh_a+eh_b*eh_b) >= minEmf\n' ...
        '    th_lpf=atan2(-eh_a,eh_b); th_raw=mod(th_lpf+atan2(we_h,emfCut),2*pi);\n' ...
        '    dth=atan2(sin(th_raw-th_h),cos(th_raw-th_h)); omega_raw=dth/dt;\n' ...
        '    b=dt*speedCut/(1+dt*speedCut); we_h=we_h+b*(omega_raw-we_h); th_h=th_raw;\n' ...
        'end\n' ...
        'if useSmo && t >= enableT, th_ctrl=th_h; wm_ctrl=we_h/pp; else, th_ctrl=th_true; wm_ctrl=wm_true; end\n' ...
        'err=atan2(sin(th_h-th_true),cos(th_h-th_true));\n' ...
        'y=zeros(5,1); y(1)=th_ctrl; y(2)=wm_ctrl; y(3)=th_h; y(4)=we_h/pp; y(5)=err;\n' ...
        'end\n'], motor.Vdc, sim_params.Ts, motor.Rs, motor.Ls, motor.pole_pairs, ...
        smo.Kslide, smo.boundary, smo.emf_lpf_cutoff, smo.speed_lpf_cutoff, ...
        smo.min_emf, smo.enable_time, useSmo);
end
